name: SSE CI/CD
on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: sudo apt-get install clang-format
      - name: Run style check
        run: clang-format -n -Werror src/* tests/*.cpp
    
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: sudo apt-get install cmake libyaml-cpp-dev libeigen3-dev libboost-test-dev
      - name: Run CMake
        run: mkdir build && cd build && cmake ..
      - name: Run make
        run: cd build && make
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            build/testsidemade
            build/CTestTestfile.cmake
          retention-days: 1

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: sudo apt-get install cmake libyaml-cpp-dev libeigen3-dev libboost-test-dev
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build/
      - name: Run tests
        run: cd build && ctest
