name: SSE CI/CD
on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: apt-get install clang-format
      - name: Run style check
        run: clang-format -n src/* tests/*
